# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://web.supnewz.com"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Sup Newz Web

# Short description of your site
description: Sup Newz merupakan situs yang membahas informasi terkini, K-POP, Anime, Donghua, Sinopsis film dan banyak lainnya.

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Kategori: "https://www.supnewz.com/categories/"
  Info Lomba:
    - SD: "https://www.supnewz.com/"
    - SMP: "https://www.supnewz.com/"
    - SMA: "https://www.supnewz.com/"
  Pengumuman: "https://www.supnewz.com/"
  PPPTK: "https://www.supnewz.com/"
  CPNS: "https://www.supnewz.com/"
  Mapel:
    - MTK: "https://www.supnewz.com/"
    - PKN: "https://www.supnewz.com/"

#  Resources:
#    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
#    - Learn markdown: "http://www.markdowntutorial.com/"
#    - GitHub Pages: "https://pages.github.com/"
#  Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: /favicon.svg

# --- Background colour/image options --- #

# By default, the navigation bar and footer have a light gray background, and the main page
# has a white background. You can specify a different background colour or a background image
# for the navigation bar, the main page, and the footer.
# navbar-col: "orange"
# navbar-img: "/img/bgimage.png"
# footer-col: "blue"
# footer-img: "/img/bgimage.png"
# page-col: "#FF0000"
# page-img: "/img/bgimage.png"

show_siderecent: false
show_sidecategory: false
show_sidetags: false

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Tim Sup Newz
  email: "sanis@my.id"
  facebook: 
  github: 
  twitter: 
  linkedin: frederik-kratzert-226a33148
  xing: yourname
  stackoverflow: yourlink


# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: false
  twitter: false
  github: false
  linkedin: false
  xing: false
  stackoverflow: false


# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  whatsapp: true
  telegram: true
  linkedin: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "btth.netlify.app"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: "kratzertblog"

# Fill in your Google Analytics ID to track your website using GA
# ---- google_analytics: "UA-96660715-1"
google_analytics: "G-LFBW8KWLJ7"

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Related Post Setting
# type by tags categories random
# src https://www.jsware.io/jekyll-related-posts/about.html
related_limit: 2
related_by: tags
related_categories:

collections:
  pages:
    output: true
    permalink: /:title/
  kontributor:
    output: true
  karakter:
    output: true
    
# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
# /:year/:month/:day/:title
timezone: "Asia/Makassar"
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 10

kramdown:
  input: GFM
  
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
      excerpt: ""
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-last-modified-at

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
